//! Fixtures generated by executing legacy two-bot service.ts and rankText
//! at docs/parity.md's frozen revision d5d11793 (en-US locale).

use two_bot_core::leveling::{level_for_xp, rank_text, total_xp_for_level};

#[test]
fn curves_and_rank_replies_match_executed_legacy() {
    let fixture: serde_json::Value =
        serde_json::from_str(include_str!("fixtures/leveling_legacy.json")).unwrap();
    for curve in fixture["curves"].as_array().unwrap() {
        let level = curve["level"].as_u64().unwrap();
        assert_eq!(total_xp_for_level(level), curve["xp"].as_u64().unwrap());
    }
    for sample in fixture["levels"].as_array().unwrap() {
        let xp = sample["xp"].as_u64().unwrap();
        assert_eq!(level_for_xp(xp), sample["level"].as_u64().unwrap());
    }
    for profile in fixture["profiles"].as_array().unwrap() {
        assert_eq!(
            rank_text(
                profile["display"].as_str().unwrap(),
                profile["level"].as_u64().unwrap(),
                Some(profile["rank"].as_u64().unwrap()),
                profile["memberCount"].as_u64().unwrap(),
                profile["xp"].as_u64().unwrap(),
            ),
            profile["content"].as_str().unwrap(),
        );
    }
}
