use serde_json::{json, Value};
use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use two_bot_core::automod::AutomodConfig;
use two_bot_core::commands::{
    CommandDefinition, CommandOptionType, PERM_BAN_MEMBERS, PERM_KICK_MEMBERS,
    PERM_MANAGE_CHANNELS, PERM_MANAGE_EVENTS, PERM_MANAGE_GUILD, PERM_MANAGE_MESSAGES,
    PERM_MODERATE_MEMBERS,
};
use two_bot_core::community::{ClassifierConfig, ScorecardGates};
use two_bot_core::feature_commands::FeatureGates;
use two_bot_core::moderation::ModerationGates;
use two_bot_core::onboarding::OnboardingGates;
use two_bot_core::router::{InteractionRouter, RouterGates};
use two_bot_core::settings::{classify_key, SettingClass, HOT_WIRED, SETTING_CLASSES};

const COMMAND_INTRO: &str = "# Command reference\n\n\
<!-- Generated by crates/core/tests/reference_docs.rs; do not edit. -->\n\n\
This is the compiled built-in publication set with all feature gates enabled,\n\
not a claim that every handler is wired or enabled in a deployment. Runtime\n\
guild fences, feature gates and handler checks still apply. See [parity](parity.md).\n\n\
The router publishes one complete set: first definition wins, built-in names\n\
are reserved, and Discord's 100-command limit applies. Database-backed custom\n\
commands and optional text triggers are dynamic and are not listed here.\n\n\
The voice commands publish only while `TWO_VOICE=1`, and `/templateassistant`\n\
also needs `TWO_ASSISTANT_ENDPOINT`; both are enabled here. The voice `kick`\n\
loses first-wins to moderation `/kick`, so the `/kick` below is the moderation\n\
command and the vote-kick shape is not listed.\n\n\
Bounds below are registry bounds; a dash means no bound is declared there,\n\
not that handler validation is unlimited. Permissions are Discord default\n\
member-permission bitfields, not a replacement for runtime authorization.\n\n";

const CONFIG_INTRO: &str = "# Configuration reference\n\n\
<!-- Generated by crates/core/tests/reference_docs.rs; do not edit. -->\n\n\
Keys and classes come from `settings::SETTING_CLASSES`; descriptions come from\n\
its checked documentation supplement (`tests/fixtures/reference_settings.json`).\n\
Defaults shown as JSON are parsed values from typed loaders given an empty map,\n\
never the process environment, a database or a deployment. Flags commonly use\n\
`1` to enable; JSON booleans describe the resulting state, not the env syntax.\n\
“Not specified in Next” means no default is supplied by this reference's typed\n\
loaders or the classification-only catalog; it does not imply a legacy default,\n\
a required value or an implemented consumer. Secret defaults are never rendered.\n\n\
- `env_only`: never dashboard-stored. Unknown names and `TWO_INTERNAL_*` fail closed.\n\
- `cold` / `hot`: legacy-catalog storage classes, not application promises.\n\
  The Container startup (`crates/bot/src/main.rs`) constructs no settings\n\
  cache/store, poller or reload consumer, so no stored (`guild_settings`)\n\
  value is read at boot or on reload — including after a restart. A\n\
  database-only value such as `TWO_AUTOMATIONS=1` stays disabled. Keys in\n\
  legacy `HOT_WIRED` are labeled “reload-report hot” (the `RefreshReport::hot`\n\
  partition in `settings.rs`); every other storable key reports cold.\n\n\
Gateway boot reads process environment only, through a fixed set of loaders:\n\
`Config::from_env` (`DISCORD_TOKEN`, `DATABASE_URL`, `LISTEN_ADDR`, `GUILD_ID`),\n\
`StickyRuntime::from_env` (`FeatureGates`: `TWO_AUTOMATIONS`, `TWO_ANNOUNCEMENTS`,\n\
`TWO_TEXT_COMMANDS`, `TWO_FEED_POLL_SECONDS`; `ModerationGates`: `TWO_MODERATION`,\n\
`TWO_OWEN_USER_ID`, `TWO_MODERATION_PROTECTED_ROLE_IDS`; plus `DISCORD_API_BASE`),\n\
and `intents_from_env` (`TWO_AUTOMOD`, `DISCORD_TICKET_CATEGORY_ID`,\n\
`DISCORD_TICKET_STAFF_ROLE_ID`, `DISCORD_TICKET_PANEL_CHANNEL_ID`), with\n\
`DISCORD_GATEWAY_URL` as a loopback-only test override. Rows for storable keys\n\
read this way say “env at boot”; every other storable row's stored value is\n\
unwired, and `env_only` rows are never dashboard-stored.\n\
Onboarding, automod, scorecard and classifier typed loaders exist but are not\n\
called during boot; their defaults below come from empty-map calls. The separate\n\
`preflight` operator CLI validates further catalog keys from the environment\n\
(channel references, panels, onboarding mode) as a read-only pre-deploy check;\n\
it applies nothing to the running gateway.\n\n\
## Container bootstrap\n\n\
`Config` separately reads `DISCORD_TOKEN`, `DATABASE_URL`, `LISTEN_ADDR` and\n\
`GUILD_ID` (see `crates/core/src/config.rs`). These are not aliases automatically\n\
resolved from legacy `TWO_DATABASE_URL` / `DISCORD_GUILD_ID`. Token, database URL\n\
and guild ID have no embedded deployment value; the listen address defaults to\n\
`0.0.0.0:8080`. Missing configuration is not proof of readiness.\n\n\
### Shutdown\n\n\
SIGTERM/SIGINT flips `/readyz` to 503, stops gateway intake, drains accepted\n\
dispatches and jobs, commits the gateway checkpoint and closes the pool. The\n\
whole drain is bounded by `SHUTDOWN_TIMEOUT_SECONDS` (whole seconds, 1–900;\n\
default 35 = the 30 s dispatch drain plus 5 s margin). Past the bound the process\n\
logs `shutdown_deadline_exceeded` and exits 1, so the supervisor restarts from the\n\
last committed checkpoint; a blocking checkpoint writer cannot be abandoned\n\
safely. A second SIGTERM/SIGINT exits 1 immediately. The Container stop\n\
grace period (SIGTERM, 15 minutes, SIGKILL) is a wrangler setting and is not\n\
configured here.\n\n\
Under the Worker, the Container also receives the reviewed `TWO_*` runtime\n\
flags in `wrangler/src/container-env.ts` (`FORWARDED_FLAGS`), forwarded\n\
verbatim when the Worker env defines them as strings. Secrets never pass\n\
through that allowlist: a Container secret needs its own explicit line in\n\
`containerEnvVars` (`wrangler/src/index.ts`), like `DISCORD_TOKEN` and\n\
`DATABASE_URL`. Every other `TWO_*` name the Rust sources mention sits in\n\
`NOT_FORWARDED` with a reason, and `wrangler/test/container-env.test.ts`\n\
fails when a name is in neither list.\n\n\
## Settings catalog\n\n\
Default sources (parsed defaults only, not boot wiring): feature/announcement\n\
gates (`feature_commands.rs`), moderation (`moderation.rs`), onboarding\n\
(`onboarding.rs`), automod (`automod.rs`), scorecard and classifier\n\
(`community.rs`). An empty ID list never contains a live ID.\n\n";

/// Catalog keys with an implemented boot-time process-environment read
/// (`StickyRuntime::from_env` gates and gateway intents). Every other
/// storable key's value has no runtime consumer: a database-only setting
/// stays inert after restart, and onboarding/automod/scorecard/classifier
/// loaders below supply defaults without being called during boot.
const BOOT_ENV: &[&str] = &[
    "TWO_AUTOMATIONS",
    "TWO_ANNOUNCEMENTS",
    "TWO_TEXT_COMMANDS",
    "TWO_FEED_POLL_SECONDS",
    "TWO_AUTOMOD",
    "DISCORD_TICKET_CATEGORY_ID",
    "DISCORD_TICKET_STAFF_ROLE_ID",
    "DISCORD_TICKET_PANEL_CHANNEL_ID",
];

fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

fn markdown_cell(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('|', "&#124;")
        .replace('`', "&#96;")
        .replace(['\r', '\n'], " ")
}

fn json_cell(value: &Value) -> String {
    format!("`{}`", markdown_cell(&value.to_string()))
}

fn permissions(command: &CommandDefinition) -> String {
    let Some(raw) = &command.default_member_permissions else {
        return "Everyone (no default permission gate)".to_owned();
    };
    let bits: u64 = raw.parse().expect("decimal permission bitfield");
    let mut remaining = bits;
    let mut names = Vec::new();
    for (flag, name) in [
        (PERM_KICK_MEMBERS, "KickMembers"),
        (PERM_BAN_MEMBERS, "BanMembers"),
        (PERM_MANAGE_CHANNELS, "ManageChannels"),
        (PERM_MANAGE_GUILD, "ManageGuild"),
        (PERM_MANAGE_MESSAGES, "ManageMessages"),
        (PERM_MANAGE_EVENTS, "ManageEvents"),
        (PERM_MODERATE_MEMBERS, "ModerateMembers"),
    ] {
        if bits & flag != 0 {
            names.push(name.to_owned());
            remaining &= !flag;
        }
    }
    if remaining != 0 {
        names.push(format!("unmapped bits {remaining}"));
    }
    format!("{} (`{raw}`)", names.join(" + "))
}

fn render_commands() -> String {
    let mut commands = InteractionRouter::new(RouterGates {
        configured_guild: None,
        scorecard: true,
        automations: true,
        announcements: true,
        moderation: true,
        voice: true,
        voice_assistant: true,
        tickets: true,
        self_roles: true,
        onboarding_picker: true,
        session_picker: true,
    })
    .publish_set(&[])
    .expect("compiled built-in registry");
    commands.sort_by(|a, b| a.name.cmp(&b.name));
    let mut output = COMMAND_INTRO.to_owned();
    writeln!(output, "Built-in commands: {}.\n", commands.len()).unwrap();
    for command in commands {
        writeln!(output, "## `/{}`", command.name).unwrap();
        writeln!(output, "\n{}\n", markdown_cell(&command.description)).unwrap();
        writeln!(output, "- Default permissions: {}", permissions(&command)).unwrap();
        writeln!(output, "- Available in DMs: {}\n", command.dm_permission).unwrap();
        if command.options.is_empty() {
            output.push_str("No options.\n\n");
            continue;
        }
        output.push_str(
            "| Option | Type | Required | Min | Max | Max length | Choices | Description |\n\
                         | --- | --- | --- | --- | --- | --- | --- | --- |\n",
        );
        for option in command.options {
            let kind = match option.kind {
                n if n == CommandOptionType::String.as_u8() => "string",
                n if n == CommandOptionType::Integer.as_u8() => "integer",
                n if n == CommandOptionType::Boolean.as_u8() => "boolean",
                n if n == CommandOptionType::User.as_u8() => "user",
                n if n == CommandOptionType::Channel.as_u8() => "channel",
                n if n == CommandOptionType::Role.as_u8() => "role",
                n if n == CommandOptionType::Attachment.as_u8() => "attachment",
                n => panic!("document new command option type {n}"),
            };
            let choices = if option.choices.is_empty() {
                "—".to_owned()
            } else {
                option
                    .choices
                    .iter()
                    .map(|choice| {
                        format!(
                            "{} = {}",
                            markdown_cell(&choice.name),
                            json_cell(&json!(choice.value))
                        )
                    })
                    .collect::<Vec<_>>()
                    .join("; ")
            };
            writeln!(
                output,
                "| `{}` | {kind} | {} | {} | {} | {} | {choices} | {} |",
                markdown_cell(&option.name),
                option.required.unwrap_or(false),
                option.min_value.map_or("—".to_owned(), |v| v.to_string()),
                option.max_value.map_or("—".to_owned(), |v| v.to_string()),
                option.max_length.map_or("—".to_owned(), |v| v.to_string()),
                markdown_cell(&option.description),
            )
            .unwrap();
        }
        output.push('\n');
    }
    output.trim_end_matches('\n').to_owned() + "\n"
}

fn setting_defaults() -> BTreeMap<&'static str, Value> {
    let empty = HashMap::new();
    let features = FeatureGates::from_map(&empty).unwrap();
    let moderation = ModerationGates::from_map(&empty).unwrap();
    let onboarding = OnboardingGates::from_map(&empty).unwrap();
    let automod = AutomodConfig::from_map(&empty).unwrap();
    let scorecard = ScorecardGates::from_map(&empty).unwrap();
    let classifier = ClassifierConfig::from_map(&empty);
    BTreeMap::from([
        ("TWO_AUTOMATIONS", json!(features.automations)),
        ("TWO_ANNOUNCEMENTS", json!(features.announcements)),
        ("TWO_TEXT_COMMANDS", json!(features.text_commands)),
        ("TWO_FEED_POLL_SECONDS", json!(features.feed_poll_seconds)),
        ("TWO_MODERATION", json!(moderation.enabled)),
        ("TWO_OWEN_USER_ID", json!(moderation.owen_user_id)),
        ("TWO_MODERATION_PROTECTED_ROLE_IDS", json!(moderation.protected_role_ids)),
        ("TWO_ONBOARDING_MODE", json!(onboarding.mode.as_str())),
        ("TWO_ONBOARDING_DRY_RUN", json!(onboarding.dry_run)),
        ("TWO_AUTOMOD", json!(automod.enabled)),
        ("TWO_AUTOMOD_ENFORCE", json!(!automod.dry_run)),
        ("TWO_AUTOMOD_BAD_WORDS", json!(automod.policy.bad_words)),
        ("TWO_AUTOMOD_BLOCKED_ATTACHMENT_EXTENSIONS", json!(automod.policy.blocked_attachment_extensions)),
        ("TWO_AUTOMOD_ALLOWED_DOMAINS", json!(automod.policy.allowed_domains)),
        ("TWO_AUTOMOD_REPEAT_COUNT", json!(automod.policy.repeated_message_count)),
        ("TWO_AUTOMOD_REPEAT_WINDOW_SECONDS", json!(automod.policy.repeated_message_window_seconds)),
        ("TWO_AUTOMOD_MENTION_LIMIT", json!(automod.policy.mention_limit)),
        ("TWO_AUTOMOD_BYPASS_ROLE_IDS", json!(automod.policy.bypass_role_ids)),
        ("TWO_AUTOMOD_EXEMPT_CHANNEL_IDS", json!(automod.policy.exempt_channel_ids)),
        ("TWO_AUTOMOD_SANCTIONS", json!(automod.policy.sanctions.iter().map(|s| {
            json!({"violations": s.violations, "action": s.action.as_str(), "timeout_seconds": s.timeout_seconds})
        }).collect::<Vec<_>>())),
        ("TWO_COMMUNITY_SCORECARD", json!(scorecard.enabled)),
        ("TWO_COMMUNITY_RECOMMENDATIONS", json!(scorecard.recommendations_enabled)),
        ("TWO_COMMUNITY_CORRECTION_CYCLES", json!(scorecard.correction_cycles)),
        ("TWO_COMMUNITY_CLASSIFIER_VERSION", json!(classifier.version)),
        ("TWO_COMMUNITY_AUTOMATION_ACTOR_IDS", json!(classifier.automation_actor_ids)),
        ("TWO_COMMUNITY_RAID_ACTOR_IDS", json!(classifier.raid_actor_ids)),
        ("TWO_COMMUNITY_STAGING_GUILD_IDS", json!(classifier.staging_guild_ids)),
        ("TWO_COMMUNITY_STAGING_ACTOR_IDS", json!(classifier.staging_actor_ids)),
        ("TWO_COMMUNITY_TEST_ACTOR_IDS", json!(classifier.test_actor_ids)),
    ])
}

fn render_configuration() -> String {
    let descriptions: BTreeMap<String, String> =
        serde_json::from_str(include_str!("fixtures/reference_settings.json")).unwrap();
    let keys: BTreeSet<_> = SETTING_CLASSES.iter().map(|(key, _)| *key).collect();
    assert_eq!(keys.len(), SETTING_CLASSES.len(), "duplicate catalog key");
    assert_eq!(
        keys,
        descriptions.keys().map(String::as_str).collect(),
        "update the settings description supplement with the catalog"
    );
    let defaults = setting_defaults();
    assert!(defaults.keys().all(|key| keys.contains(key)));
    let mut settings = SETTING_CLASSES.to_vec();
    settings.sort_by_key(|(key, _)| *key);
    let mut output = CONFIG_INTRO.to_owned();
    writeln!(output, "Catalog entries: {}.\n", settings.len()).unwrap();
    output.push_str(
        "| Key | Class | Parsed default | Application | Description |\n\
                     | --- | --- | --- | --- | --- |\n",
    );
    for (key, class) in settings {
        let boot_read = BOOT_ENV.contains(&key);
        let hot_wired = HOT_WIRED.contains(&key);
        let (class, application) = match class {
            SettingClass::EnvOnly => ("env_only", "environment only"),
            SettingClass::Cold if boot_read => ("cold", "env at boot; stored unwired"),
            SettingClass::Cold => ("cold", "stored unwired"),
            SettingClass::Hot if hot_wired => ("hot", "stored unwired (reload-report hot)"),
            SettingClass::Hot if boot_read => ("hot", "env at boot; stored unwired"),
            SettingClass::Hot => ("hot", "stored unwired"),
        };
        let default = if is_secret_key(key) {
            "Not rendered (secret)".to_owned()
        } else {
            defaults
                .get(key)
                .map_or_else(|| "Not specified in Next".to_owned(), json_cell)
        };
        let description = &descriptions[key];
        assert!(!description.trim().is_empty(), "description for {key}");
        writeln!(
            output,
            "| `{key}` | {class} | {default} | {application} | {} |",
            markdown_cell(description)
        )
        .unwrap();
    }
    output
}

fn is_secret_key(key: &str) -> bool {
    [
        "TOKEN",
        "SECRET",
        "DATABASE_URL",
        "ACCESS_KEY",
        "PSEUDONYM_KEY",
    ]
    .iter()
    .any(|marker| key.contains(marker))
}

fn generated_documents() -> [(&'static str, String); 2] {
    [
        ("docs/commands.md", render_commands()),
        ("docs/configuration.md", render_configuration()),
    ]
}

fn check_document(path: &str, committed: &str, generated: &str) -> Result<(), String> {
    if committed == generated {
        Ok(())
    } else {
        Err(format!(
            "{path} is stale; regenerate with: python3 scripts/cargo_cache.py run -- test \
             -p two-bot-core --test reference_docs regenerate_reference_docs -- --ignored"
        ))
    }
}

#[test]
fn committed_references_match_compiled_metadata() {
    for (path, generated) in generated_documents() {
        let committed = std::fs::read_to_string(repository_root().join(path)).unwrap();
        assert_eq!(
            committed,
            generated,
            "{}",
            check_document(path, &committed, &generated)
                .err()
                .unwrap_or_default()
        );
    }
}

#[test]
fn rejects_deliberately_stale_documents() {
    for (path, generated) in generated_documents() {
        let stale = format!("{generated}\nDeliberately stale fixture.\n");
        let error = check_document(path, &stale, &generated).unwrap_err();
        assert!(error.contains(path));
        assert!(error.contains("regenerate_reference_docs"));
        assert!(check_document(path, &generated, &generated).is_ok());
    }
}

#[test]
fn boot_env_keys_are_catalogued_storable_keys() {
    let keys: BTreeSet<_> = SETTING_CLASSES.iter().map(|(key, _)| *key).collect();
    for key in BOOT_ENV {
        assert!(keys.contains(key), "{key} is not a catalog key");
        assert!(
            matches!(
                classify_key(key),
                Some(SettingClass::Cold | SettingClass::Hot)
            ),
            "{key} is env-only; its row never consults BOOT_ENV"
        );
    }
}

#[test]
fn references_contain_no_snowflakes_or_secret_defaults() {
    let snowflake = regex::Regex::new(r"\b[0-9]{17,20}\b").unwrap();
    for (_, document) in generated_documents() {
        assert!(
            !snowflake.is_match(&document),
            "references must not embed live IDs"
        );
    }
    let defaults = setting_defaults();
    assert!(defaults.keys().all(|key| !is_secret_key(key)));
}

#[test]
fn escapes_markdown_metadata() {
    assert_eq!(
        markdown_cell("a|b\n<value> & `code`"),
        "a&#124;b &lt;value&gt; &amp; &#96;code&#96;"
    );
}

#[test]
#[ignore = "explicitly regenerate committed docs; never update during normal tests"]
fn regenerate_reference_docs() {
    for (path, generated) in generated_documents() {
        std::fs::write(repository_root().join(path), generated).unwrap();
    }
}
