//! SQLx persistence for feeds. Claims are fenced and guild-scoped; uncertain
//! sends stay pending for nonce reconciliation rather than being blindly retried.

use crate::automation_quota::{lock_quota, AutomationQuota};
use crate::feeds::{
    DeliveryClaim, FeedError, FeedKind, FeedPost, FeedRelay, DELIVERY_CLAIM_LEASE_MS,
};
use sqlx::{Pool, Postgres, Row};

#[derive(Debug, thiserror::Error)]
pub enum FeedStoreError {
    #[error("feed store database error: {0}")]
    Db(#[from] sqlx::Error),
    #[error(transparent)]
    Domain(#[from] FeedError),
    #[error("Feed claim token must not be empty.")]
    EmptyClaimToken,
    #[error("{0}")]
    Capacity(AutomationQuota),
}

/// Add is insert-only: an externally supplied id cannot hijack an existing
/// relay, or change its source while retaining that source's delivery ledger.
/// The guild's 25-definition cap includes disabled feeds, and is checked in
/// the insert transaction under a guild-scoped capacity lock.
pub async fn add_feed(pool: &Pool<Postgres>, feed: &FeedRelay) -> Result<(), FeedStoreError> {
    crate::feeds::normalize_source(feed.kind, &feed.source)?;
    let mut tx = pool.begin().await?;
    lock_quota(&mut tx, &feed.guild_id, AutomationQuota::Feeds).await?;
    let count: i64 = sqlx::query_scalar("SELECT count(*) FROM feed_relays WHERE guild_id = $1")
        .bind(&feed.guild_id)
        .fetch_one(&mut *tx)
        .await?;
    if count >= AutomationQuota::Feeds.limit() {
        return Err(FeedStoreError::Capacity(AutomationQuota::Feeds));
    }
    sqlx::query(
        "INSERT INTO feed_relays
         (id, guild_id, channel_id, kind, source, enabled, last_checked_at, created_by, created_at, updated_at)
         VALUES ($1, $2, $3, $4, $5, $6, to_timestamp($7::bigint::double precision / 1000),
                 $8, to_timestamp($9::bigint::double precision / 1000), to_timestamp($10::bigint::double precision / 1000))"
    )
    .bind(&feed.id).bind(&feed.guild_id).bind(&feed.channel_id).bind(feed.kind.as_str())
    .bind(&feed.source).bind(feed.enabled).bind(feed.last_checked_at).bind(&feed.created_by)
    .bind(feed.created_at).bind(feed.updated_at).execute(&mut *tx).await?;
    tx.commit().await?;
    Ok(())
}

pub async fn list_feeds(
    pool: &Pool<Postgres>,
    guild_id: &str,
    enabled_only: bool,
) -> Result<Vec<FeedRelay>, FeedStoreError> {
    let rows = sqlx::query(
        "SELECT id, guild_id, channel_id, kind, source, enabled, created_by,
         (extract(epoch FROM last_checked_at) * 1000)::bigint AS last_checked_ms,
         (extract(epoch FROM created_at) * 1000)::bigint AS created_ms,
         (extract(epoch FROM updated_at) * 1000)::bigint AS updated_ms
         FROM feed_relays WHERE guild_id = $1 AND (NOT $2 OR enabled) ORDER BY created_at, id",
    )
    .bind(guild_id)
    .bind(enabled_only)
    .fetch_all(pool)
    .await?;
    rows.into_iter()
        .map(|row| {
            Ok(FeedRelay {
                id: row.try_get("id")?,
                guild_id: row.try_get("guild_id")?,
                channel_id: row.try_get("channel_id")?,
                kind: FeedKind::parse(row.try_get("kind")?)?,
                source: row.try_get("source")?,
                enabled: row.try_get("enabled")?,
                last_checked_at: row.try_get("last_checked_ms")?,
                created_by: row.try_get("created_by")?,
                created_at: row.try_get("created_ms")?,
                updated_at: row.try_get("updated_ms")?,
            })
        })
        .collect()
}

pub async fn remove_feed(
    pool: &Pool<Postgres>,
    guild_id: &str,
    id: &str,
) -> Result<bool, FeedStoreError> {
    Ok(
        sqlx::query("DELETE FROM feed_relays WHERE guild_id = $1 AND id = $2")
            .bind(guild_id)
            .bind(id)
            .execute(pool)
            .await?
            .rows_affected()
            == 1,
    )
}

/// Single-statement conflict arbitration. The arbiter is intentionally
/// omitted: `feed_deliveries` carries two unique keys (the PK on
/// `(feed_id, item_key)` plus `UNIQUE (feed_id, nonce)`), and an arbiter
/// pinned to only one of them still raises `unique_violation` on the other
/// under concurrent identical inserts — index entries land non-atomically,
/// so a racer can miss the arbiter conflict yet hit the sibling one (seen
/// on CI: 16 parallel claims colliding on the nonce key). Bare
/// `ON CONFLICT DO NOTHING` arbitrates on both; any conflict means this
/// item (or its deterministic nonce) is already claimed, so fall through to
/// the lease-takeover attempt below.
/// Only expired pending claims can be taken over; completed rows remain
/// permanent across process/pool restarts.
/// Tokens must be unique for each acquisition attempt (generated by adapter).
pub async fn claim_delivery(
    pool: &Pool<Postgres>,
    guild_id: &str,
    post: &FeedPost,
    token: &str,
    now_ms: i64,
) -> Result<Option<DeliveryClaim>, FeedStoreError> {
    if let Some(claim) = claim_fresh_delivery(pool, guild_id, post, token, now_ms).await? {
        return Ok(Some(claim));
    }
    let reclaimed = sqlx::query(
        "UPDATE feed_deliveries d SET claim_token = $3, claimed_at = to_timestamp($4::bigint::double precision / 1000)
         FROM feed_relays f WHERE d.feed_id = $1 AND d.item_key = $2 AND d.state = 'pending'
         AND (d.claimed_at IS NULL OR d.claimed_at <= to_timestamp($5::bigint::double precision / 1000))
         AND f.id = d.feed_id AND f.guild_id = $6 AND f.channel_id = $7 AND f.enabled"
    ).bind(&post.feed_id).bind(&post.item_key).bind(token).bind(now_ms)
        .bind(now_ms.saturating_sub(DELIVERY_CLAIM_LEASE_MS)).bind(guild_id).bind(&post.channel_id)
        .execute(pool).await?.rows_affected();
    Ok((reclaimed == 1).then_some(DeliveryClaim::Recovered))
}

/// XML candidates may acquire only never-claimed items. Recovery has its own
/// bounded oldest-first queue: taking over skipped rows here would rotate their
/// leases without examining history, starving them behind the same first page.
pub async fn claim_fresh_delivery(
    pool: &Pool<Postgres>,
    guild_id: &str,
    post: &FeedPost,
    token: &str,
    now_ms: i64,
) -> Result<Option<DeliveryClaim>, FeedStoreError> {
    if token.is_empty() {
        return Err(FeedStoreError::EmptyClaimToken);
    }
    let inserted = sqlx::query(
        "INSERT INTO feed_deliveries
         (feed_id, item_key, nonce, state, first_seen_at, claim_token, claimed_at)
         SELECT id, $2, $3, 'pending', to_timestamp($5::bigint::double precision / 1000),
                $4, to_timestamp($5::bigint::double precision / 1000)
         FROM feed_relays WHERE id = $1 AND guild_id = $6 AND channel_id = $7 AND enabled
         ON CONFLICT DO NOTHING",
    )
    .bind(&post.feed_id)
    .bind(&post.item_key)
    .bind(&post.nonce)
    .bind(token)
    .bind(now_ms)
    .bind(guild_id)
    .bind(&post.channel_id)
    .execute(pool)
    .await?
    .rows_affected();
    Ok((inserted == 1).then_some(DeliveryClaim::Fresh))
}

/// Recovery must not depend on an item remaining in the current feed document.
/// Oldest leases are examined first; reacquisition moves an unresolved row to
/// the back of this bounded queue instead of starving later pending claims.
pub async fn pending_deliveries(
    pool: &Pool<Postgres>,
    feed: &FeedRelay,
    now_ms: i64,
    limit: u32,
) -> Result<Vec<FeedPost>, FeedStoreError> {
    let rows = sqlx::query(
        "SELECT d.item_key, d.nonce FROM feed_deliveries d
         JOIN feed_relays f ON f.id = d.feed_id
         WHERE f.id = $1 AND f.guild_id = $2 AND f.channel_id = $3 AND f.enabled
         AND d.state = 'pending'
         AND (d.claimed_at IS NULL OR d.claimed_at <= to_timestamp($4::bigint::double precision / 1000))
         ORDER BY d.claimed_at NULLS FIRST, d.item_key LIMIT $5",
    )
    .bind(&feed.id)
    .bind(&feed.guild_id)
    .bind(&feed.channel_id)
    .bind(now_ms.saturating_sub(DELIVERY_CLAIM_LEASE_MS))
    .bind(i64::from(limit.min(200)))
    .fetch_all(pool)
    .await?;
    rows.into_iter()
        .map(|row| {
            Ok(FeedPost {
                feed_id: feed.id.clone(),
                channel_id: feed.channel_id.clone(),
                item_key: row.try_get("item_key")?,
                nonce: row.try_get("nonce")?,
                // Recovered claims only reconcile history; this is never sent.
                content: String::new(),
                suppress_mentions: true,
                enforce_nonce: true,
            })
        })
        .collect()
}

pub async fn mark_delivered(
    pool: &Pool<Postgres>,
    guild_id: &str,
    post: &FeedPost,
    token: &str,
    message_id: &str,
    now_ms: i64,
) -> Result<bool, FeedStoreError> {
    Ok(sqlx::query(
        "UPDATE feed_deliveries d SET state = 'delivered', message_id = $4,
         delivered_at = to_timestamp($5::bigint::double precision / 1000), claim_token = NULL, claimed_at = NULL
         FROM feed_relays f WHERE d.feed_id = $1 AND d.item_key = $2 AND d.claim_token = $3
         AND d.state = 'pending' AND f.id = d.feed_id AND f.guild_id = $6"
    ).bind(&post.feed_id).bind(&post.item_key).bind(token).bind(message_id).bind(now_ms)
        .bind(guild_id).execute(pool).await?.rows_affected() == 1)
}

/// Only for an acquired item known never to have been sent (e.g. poll-cap
/// deferral). NEVER call this on a timeout, ambiguous HTTP result or DB error
/// after sending: retain the row and reconcile its nonce on a later poll.
pub async fn release_unposted(
    pool: &Pool<Postgres>,
    guild_id: &str,
    post: &FeedPost,
    token: &str,
) -> Result<bool, FeedStoreError> {
    Ok(sqlx::query(
        "DELETE FROM feed_deliveries d USING feed_relays f WHERE d.feed_id = $1
         AND d.item_key = $2 AND d.claim_token = $3 AND d.state = 'pending'
         AND f.id = d.feed_id AND f.guild_id = $4",
    )
    .bind(&post.feed_id)
    .bind(&post.item_key)
    .bind(token)
    .bind(guild_id)
    .execute(pool)
    .await?
    .rows_affected()
        == 1)
}

pub async fn mark_checked(
    pool: &Pool<Postgres>,
    guild_id: &str,
    id: &str,
    now_ms: i64,
) -> Result<(), FeedStoreError> {
    sqlx::query("UPDATE feed_relays SET last_checked_at = to_timestamp($3::bigint::double precision / 1000) WHERE guild_id = $1 AND id = $2")
        .bind(guild_id).bind(id).bind(now_ms).execute(pool).await?;
    Ok(())
}

pub struct FeedAudit<'a> {
    pub id: &'a str,
    pub guild_id: &'a str,
    pub actor_id: Option<&'a str>,
    pub action: &'a str,
    pub target_key: &'a str,
    pub outcome: &'a str,
    pub reason: Option<&'a str>,
    pub now_ms: i64,
}

pub async fn write_audit(
    pool: &Pool<Postgres>,
    audit: &FeedAudit<'_>,
) -> Result<(), FeedStoreError> {
    sqlx::query(
        "INSERT INTO announcements_audit_log (id, guild_id, actor_id, action, target_key, outcome, reason, created_at)
         VALUES ($1, $2, $3, $4, $5, $6, $7, to_timestamp($8::bigint::double precision / 1000))"
    ).bind(audit.id).bind(audit.guild_id).bind(audit.actor_id).bind(audit.action)
        .bind(audit.target_key).bind(audit.outcome).bind(audit.reason).bind(audit.now_ms)
        .execute(pool).await?;
    Ok(())
}
